# Generated by Django 2.1.3 on 2019-03-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydiaborder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField(default=0)),
                ('OrderDate', models.DateField(null=True)),
                ('OrderRef', models.CharField(max_length=200)),
                ('OrderForeignRef', models.CharField(max_length=200)),
                ('OrderInitiator', models.CharField(max_length=200)),
                ('OrderUser', models.CharField(max_length=200)),
                ('OrderStatus', models.IntegerField(default=21)),
                ('OrderSubmitDate', models.DateField(null=True)),
                ('OrderCancellationDate', models.DateField(null=True)),
                ('OrderCloseDate', models.DateField(null=True)),
                ('OrderIntegrationRequestID', models.CharField(max_length=200)),
                ('OrderSession', models.CharField(max_length=200)),
                ('OrderCostCenter', models.CharField(max_length=200)),
                ('OrderOwnerOrgID', models.CharField(max_length=200)),
            ],
        ),
    ]
