# Generated by Django 2.1.3 on 2019-03-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0002_mydiaborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydiaborder',
            old_name='OrderCostCenter',
            new_name='OrderCC',
        ),
        migrations.RenameField(
            model_name='mydiaborder',
            old_name='OrderOwnerOrgID',
            new_name='OrderOwner',
        ),
        migrations.AlterField(
            model_name='mydiaborder',
            name='OrderForeignRef',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mydiaborder',
            name='OrderIntegrationRequestID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mydiaborder',
            name='OrderRef',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
