# Generated by Django 2.1.3 on 2019-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0003_auto_20190310_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydiabautorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_visitor', models.BooleanField(default=True)),
                ('EntryDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
