# Generated by Django 2.1.7 on 2019-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0005_mydiabrichblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabrichblog',
            name='BlogHtml',
            field=models.TextField(default='<html><body><p>start<p></body></html>'),
            preserve_default=False,
        ),
    ]
