# Generated by Django 2.1.7 on 2019-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0006_mydiabrichblog_bloghtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabrichblog',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
