# Generated by Django 2.1.7 on 2019-03-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0007_mydiabrichblog_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='MydiabComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentDate', models.DateTimeField(verbose_name='date published')),
                ('CommentRich', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('BlogName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydiabprod.Mydiabrichblog')),
            ],
        ),
    ]
