# Generated by Django 2.1.7 on 2019-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0008_mydiabcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabcomments',
            name='CommentOwner',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
