# Generated by Django 2.1.7 on 2019-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0009_mydiabcomments_commentowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabrichblog',
            name='BlogOwner',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
