# Generated by Django 2.1.7 on 2019-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0010_mydiabrichblog_blogowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabrichblog',
            name='AdminRight',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
