# Generated by Django 2.1.7 on 2019-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiabprod', '0011_mydiabrichblog_adminright'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiabrichblog',
            name='BlogHash',
            field=models.TextField(default='bastag'),
        ),
    ]
